### ISSUE TITLE
ClothingGrantTagComponent can become stuck and fail to add or remove a tag.

### ISSUE THREAD

**Issue by moonheart08** [arcadia-station/arcadia-station#1415]
Similar issue applies to your components-granting version.

https://github.com/space-wizards/space-station-14/pull/14894#pullrequestreview-1359497458

**Comment by Elijahrane** [comment]
I fixed a few of the issues with park's impl, but it probably needs a full rewrite at this point

It probably just shouldn't exist and its use cases can use a helper function instead

The component granting one is a bit harder, though, because those add functionality that usually need to be on the user

**Comment by Elijahrane** [comment]
OK I just deleted that one, it's too niche and there isn't much point in adding tags to a user since they offer no additional functionality
