### ISSUE TITLE
Deep frying shader doesn't work on a lot of renderers

### ISSUE THREAD

**Issue by Elijahrane** [arcadia-station/arcadia-station#863]
## Description

So far confirmed on:
AMD Mesa (source: me)
Intel Integrated Mesa (source: @Leander-0)

**Comment by Elijahrane** [comment]
I have modified the shader to not use a reserved keyword for mesa. Let's see if anyone else has issues and close if there's no further reports within a few days.

**Comment by deltanedas** [comment]
somehow it works on proprietary novideo drivers, even though 99% of effect shaders like drugs get really glitchy

**Comment by Vordenburg** [comment]
The last known issues involving unspecified precision were fixed in the last deep fryer commit, and I haven't heard of any new issues involving the shader. I feel like we can close this for now.

For future reference, the most compatible way to write a shader for SS14 seems to be to always specify precision for all variables and function arguments, and to avoid using keywords that may be reserved on one interpreter but not another.
